#!/bin/sh /etc/rc.common
# tvled — 3 задних LED (white:signal1/2/3) показывают уровень сети LTE-модема (AT+CSQ).
USE_PROCD=1
START=96

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/tvled
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
