# microtun.conf — редактируется через /tinyvless/microtun/
DNS_FORWARD_MAX=50
DNS_CACHESIZE=300
LOG_SIZE_KB=96
REDIR_PORT=1082
TPROXY_PORT=1083
LAN_IF=br-lan
ROUTE_APPLY_DELAY=2
DNS_WATCHDOG_INTERVAL=20
TINYVLESS_NICE=10
PROCD_RESPAWN_THRESHOLD=3600
PROCD_RESPAWN_TIMEOUT=5
PROCD_RESPAWN_RETRY=5
UDP_DISCORD_PORT1=19294-19344
UDP_DISCORD_PORT2=50000-65535
DIAL_SEM=64
POOL_BUF_KB=4
TLS_CACHE=128
GO_MEM_LIMIT_MB=18
