#!/bin/sh
# check if we are on real system
if [ -z "${IPKG_INSTROOT}" ]; then
	rm -f /etc/config/zapret-opkg*
	rm -f /etc/config/zapret.opkg*
	rm -f /etc/config/zapret.apk*
	[ -f "/opt/zapret/config" ] && cp -f /opt/zapret/config "/opt/zapret/config.backup"
	#rm -rf /opt/zapret
	#echo "Directory /opt/zapret removed!"
fi
exit 0
